@echo off

set EXEC="C:\Program Files\ImageMagick-6.8.9-Q16\convert.exe"
set OUTPUT_FILE_PREFIX=Icon
set ORIGINAL_FILE=%OUTPUT_FILE_PREFIX%-76@2x.png
set ORIGINAL_FILEx2=iTunesArtwork

%EXEC% -resize 114x %ORIGINAL_FILEx2% %OUTPUT_FILE_PREFIX%@2x.png
%EXEC% -resize 144 %ORIGINAL_FILEx2% %OUTPUT_FILE_PREFIX%-72@2x.png
%EXEC% -resize 100x %ORIGINAL_FILEx2% %OUTPUT_FILE_PREFIX%-50@2x.png
%EXEC% -resize 80x  %ORIGINAL_FILEx2% %OUTPUT_FILE_PREFIX%-40@2x.png
%EXEC% -resize 120x %ORIGINAL_FILEx2% %OUTPUT_FILE_PREFIX%-60@2x.png
%EXEC% -resize 152x %ORIGINAL_FILEx2% %OUTPUT_FILE_PREFIX%-76@2x.png

pause

%EXEC% -resize 57x  %ORIGINAL_FILE% %OUTPUT_FILE_PREFIX%.png
%EXEC% -resize 72x  %ORIGINAL_FILE% %OUTPUT_FILE_PREFIX%-72.png
%EXEC% -resize 50x  %ORIGINAL_FILE% %OUTPUT_FILE_PREFIX%-Small-50.png
%EXEC% -resize 29x  %ORIGINAL_FILE% %OUTPUT_FILE_PREFIX%-Small.png
%EXEC% -resize 58x  %ORIGINAL_FILE% %OUTPUT_FILE_PREFIX%-Small@2x.png
%EXEC% -resize 40x  %ORIGINAL_FILE% %OUTPUT_FILE_PREFIX%-40.png
%EXEC% -resize 60x %ORIGINAL_FILE% %OUTPUT_FILE_PREFIX%-60.png
%EXEC% -resize 76x  %ORIGINAL_FILE% %OUTPUT_FILE_PREFIX%-76.png

pause
